name: CI

on:
  push:
  schedule:
    - cron: '6 6 * * 1/2'

jobs:
  link-test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: php-actions/composer@v6
    - uses: php-actions/phpunit@v3
      with:
        bootstrap: vendor/autoload.php
        args: --testdox tests
