name: CI

on:
  push:
  schedule:
    - cron: '12 12 * * *'

jobs:
  link-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v2
    - uses: php-actions/phpunit@v9
      with:
        bootstrap: vendor/autoload.php
        args: tests
