name: CI

on:
  push:

jobs:
  link-test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: php-actions/composer@v6
    - uses: php-actions/phpunit@v4
      with:
        bootstrap: vendor/autoload.php
        args: --testdox tests
