name: CI

on:
  push:

jobs:
  link-test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        # Ensure the pcov or xdebug extension is here if you need code coverage
        coverage: pcov
    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run Tests
      run: vendor/bin/phpunit --testdox tests
